### ISSUE TITLE
pip3-netcdf-install.sh fails to install netcdf4

### ISSUE THREAD

**Issue by mx-moth** [eReefs/netcdf-base#3]
The script is missing a `set -e`, so errors are hidden. The command that attempts to install netcdf4 fails, but the next call works so the script as a whole "succeeds".

netcdf4 fails to build because it requires numpy to be installed but does not list it as a build_requires dependency. The command immediately prior should install numpy to alleviate this. Numpy should also be added to the requirements.txt

**Comment by sharon-tickell** [comment]
Good catch - thanks for the ticket!

**Comment by sharon-tickell** [comment]
Shouldn't the netcdf library auto-install its own pure python dependencies, though?  Or is that too much to expect?

**Comment by mx-moth** [comment]
It is too much to expect. The netcdf4 library declares its Python runtime dependencies, but not its build time dependencies. They don't expect you to build your own wheels, so it isn't well supported.

**Comment by mx-moth** [comment]
According to the [netcdf4-feedstock](https://github.com/conda-forge/netcdf4-feedstock/blob/main/recipe/meta.yaml), the build time dependencies are numpy and cython. We are already installing cython.

**Comment by mx-moth** [comment]
A potential source of problems is that this script installs some collection of dependencies during the build phase to produce a functioning Python environment, but this image is also intended to be extended by other projects which will install their own dependencies. The derived images might want to install a different version of numpy than the one that netcdf4 was built against. I see that the `pip3-netcdf-install.sh` script can take a `requirements.txt` as an argument, but this is insufficient. As this script is run automatically the requirements have already been installed. The derived images will have to call `pip3-netcdf-install.sh` with their specific requirements file and hope that all the dependencies are rebuilt if required. This could get messy. Imagine installing a newer version of numpy but keeping the same version of netcdf4. Numpy will be reinstalled while netcdf4 will not be, but netcdf4 was now built against a version of numpy that is no longer installed.

This issue would be alleviated by not running `pip3-netcdf-install.sh` during the build phase, and requiring developers to run this in their derived images using their own constraints file. This will make the base python image not usable without further modification however which isn't great, especially if you wanted to provide an interactive environment out of the box!
